name: CI/CD Pipeline - Dev to Main

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run:
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Run Backend Unit Tests
        working-directory: backend
        run: npm test

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Run Frontend Unit Tests
        working-directory: frontend
        run: npm test

      - name: Run End-to-End Tests
        working-directory: e2e-tests
        run: npm install && npm test

      - name: Build Docker Images
        run: docker-compose build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Images
        run: docker-compose push
