name: CI Feature to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v3

    - name: Configurer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installer les dépendances frontend
      working-directory: frontend
      run: npm install

    - name: Installer les dépendances backend
      working-directory: backend
      run: npm install

    - name: Lancer les tests unitaires frontend
      working-directory: frontend
      run: npm test

    - name: Lancer les tests unitaires backend
      working-directory: backend
      run: npm test

  auto-merge-dev-to-main:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v3

    - name: Fusionner dev dans main
      uses: devops-infra/github-actions-merge-branch@v2
      with:
        from-branch: dev
        target-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
